install:
  - cd msvc
  - powershell -ExecutionPolicy ByPass -File downloadDependencies.ps1
  - cd ..

build_script:
  - msbuild msvc\csound-vs\Csound.sln

after_build:
  - 7z a csound.zip %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\Release\*.exe %APPVEYOR_BUILD_FOLDER%\msvc\csound-vs\Release\*.dll

artifacts:
  - path: csound.zip
    name: Csound
    type: zip

cache: msvc\vcpkg\installed\x64-windows -> msvc\downloadDependencies.ps1
